project_name: oembed-server

port: 9021
python: python2
type: flask

# Configs below will not usually change
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
deploy_dir: "{{ install_root }}/{{ project_name }}"
application_dir: "{{ deploy_dir }}"
requirements_file: "{{ deploy_dir }}/requirements.txt"
service_name: "apps/{{ project_name }}"
virtualenv: "{{ virtualenv_root }}/{{ project_name }}"
wsgi_application: "{{ deploy_config_dir }}.wsgi:application"
