project_name: oembed-server
service_name: "{{ project_name|lower }}"
gitdeploy_version: "1.0.6"
python_version: "3.8.2"
python: /home/apps/sites/oembed-server/.venv/bin/python
service_port: "{{ oembed_server_port }}"

playbooks:
  - playbook.deploy.yml
  - playbook.restart.yml

install_root: "/home/apps/sites"
deploy_dir: "{{ install_root }}/{{ project_name }}"
application_dir: "{{ deploy_dir }}"
env_file: "{{ deploy_dir }}/.env"
envrc_file: "{{ deploy_dir }}/.envrc"
virtualenv: "{{ deploy_dir }}/.venv"
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
requirements_file: "{{ deploy_dir }}/requirements.txt"
wsgi_application: "wsgi:application"
